const express = require('express')
const router = express.Router()
const {signup,login, redirect} = require('../controller/authController')
const{createmovie,getmovie, update, singlemovie,deletes}=require('../controller/movieController')
const{comments, getcomment, deletecomment}=require('../controller/commentController')
const{trendings, deletetrend, gettrend}=require('../controller/trendingMovieController')
const{ getprofile, profiles}=require('../controller/profileSetController')
const {multer,storage}= require('../middleware/multer')
const checkuser = require('../middleware/auth')
const upload = multer({storage:storage})


router.post('/sign',signup )

    router.post('/login', login)
    router.post('/create',upload.single('image'),createmovie)
    router.get('/get',getmovie)
    router.patch('/update/:id',upload.single('image'),update)
    router.get('/getsingle/:id',singlemovie)
    router.post('/comment/:reqid',comments)
    router.get('/get/:reqid',getcomment )
    router.delete('/delete/:id',deletes)
    router.post('/redirect',redirect)
    router.post('/trending',upload.single('image'),trendings)
    router.delete('/deletetrend/:id',deletetrend)
    router.get('/gettrend',gettrend)
    router.delete('/deletecomment/:id',checkuser,deletecomment)
    router.post('/profile',upload.single('image'),profiles)
    router.get('/getprofile',getprofile)
    module.exports = router;